<?php

/**
 * Class ilSWITCHdriveSettingsGUI
 *
 * @author            Theodor Truffer <tt@studer-raimann.ch>
 * @version           1.0.0
 *
 * @ilCtrl_IsCalledBy ilSWITCHdriveSettingsGUI : ilObjCloudGUI
 * @ingroup           ModulesCloud
 */
class ilSWITCHdriveSettingsGUI extends ilCloudPluginSettingsGUI {

	/**
	 * @var ilPropertyFormGUI
	 */
	protected $form;

	protected function initPluginSettings() {
        $item = new ilTextInputGUI($this->getPluginObject()->getPluginHookObject()->txt('username'), 'username');
        $item->setRequired(true);
	    $this->form->addItem($item);

        $item = new ilPasswordInputGUI($this->getPluginObject()->getPluginHookObject()->txt('password'), 'password');
        $item->setInfo($this->getPluginObject()->getPluginHookObject()->txt('password_info'));
        $item->setRetype(false);
        $item->setRequired(true);
	    $this->form->addItem($item);

        $item = new ilTextInputGUI($this->getPluginObject()->getPluginHookObject()->txt('proxy'), 'proxy');
	    $this->form->addItem($item);
    }

    protected function getPluginSettingsValues(&$values){
        $values['username'] = $this->getPluginObject()->getUsername();
        $values['password'] = $this->getPluginObject()->getPassword();
        $values['proxy'] = $this->getPluginObject()->getProxy();
    }

    public function updatePluginSettings()
    {
        $this->getPluginObject()->setUsername($this->form->getInput("username"));
        $this->getPluginObject()->setPassword($this->form->getInput("password"));
        $this->getPluginObject()->setProxy($this->form->getInput("proxy"));
        $this->getPluginObject()->doUpdate();
    }



    /**
	 * @return ilSWITCHdrive
	 */
	public function getPluginObject() {
		return parent::getPluginObject(); // TODO: Change the autogenerated stub
	}
}

?>
