<?php

/**
 * Class ilOwnCloudSettingsGUI
 *
 * @author            Theodor Truffer <tt@studer-raimann.ch>
 * @version           1.0.0
 *
 * @ilCtrl_IsCalledBy ilOwnCloudSettingsGUI : ilObjCloudGUI
 * @ingroup           ModulesCloud
 */
class ilOwnCloudSettingsGUI extends ilCloudPluginSettingsGUI {

	/**
	 * @var ilPropertyFormGUI
	 */
	protected $form;

	protected function initPluginSettings() {
        $item = new ilTextInputGUI($this->getPluginObject()->getPluginHookObject()->txt('base_uri'), 'base_uri');
        $item->setRequired(true);
	    $this->form->addItem($item);

        $item = new ilTextInputGUI($this->getPluginObject()->getPluginHookObject()->txt('username'), 'username');
        $item->setRequired(true);
	    $this->form->addItem($item);

        $item = new ilTextInputGUI($this->getPluginObject()->getPluginHookObject()->txt('password'), 'password');
        $item->setRequired(true);
	    $this->form->addItem($item);

        $item = new ilTextInputGUI($this->getPluginObject()->getPluginHookObject()->txt('proxy'), 'proxy');
	    $this->form->addItem($item);

        ilUtil::sendInfo('Bitte beachten Sie, dass die Zugangsdaten für SWITCHdrive in ILIAS gespeichert werden, und
        so von den Systemadministratoren ausgelesen werden könnten. Aus Sicherheitsgründen sollten Sie für
        unterschiedliche Webdienste auch immer unterschiedliche Passwörter verwenden.', true);
    }

    protected function getPluginSettingsValues(&$values){
        $values['base_uri'] = $this->getPluginObject()->getBaseUri();
        $values['username'] = $this->getPluginObject()->getUsername();
        $values['password'] = $this->getPluginObject()->getPassword();
        $values['proxy'] = $this->getPluginObject()->getProxy();
    }

    public function updatePluginSettings()
    {
        $this->getPluginObject()->setBaseUri($this->form->getInput("base_uri"));
        $this->getPluginObject()->setUsername($this->form->getInput("username"));
        $this->getPluginObject()->setPassword($this->form->getInput("password"));
        $this->getPluginObject()->setProxy($this->form->getInput("proxy"));
        $this->getPluginObject()->doUpdate();
    }



    /**
	 * @return ilOwnCloud
	 */
	public function getPluginObject() {
		return parent::getPluginObject(); // TODO: Change the autogenerated stub
	}
}

?>
