<?php
/* Copyright (c) 1998-2009 ILIAS open source, Extended GPL, see docs/LICENSE */

require_once('./Modules/Cloud/classes/class.ilCloudPluginCreationGUI.php');

/**
 * Class ilOwnCloudCreationGUI
 *
 * @author  Theodor Truffer <tt@studer-raimann.ch>
 */
class ilOwnCloudCreationGUI extends ilCloudPluginCreationGUI {

	const F_BASEURI = 'base_uri';
	const F_USERNAME = 'username';
	const F_PASSWORD = 'password';


	/**
	 * @param ilRadioOption $option
	 */
	public function initPluginCreationFormSection(ilRadioOption $option) {

		$item = new ilTextInputGUI($this->txt(self::F_BASEURI), self::F_BASEURI);
        $item->setRequired(true);

//
//		$option_default = new ilRadioOption($this->txt(self::F_DEFAULT_BASE_FOLDER), self::F_DEFAULT_BASE_FOLDER);
//
//		$option_custom = new ilRadioOption($this->txt('custom_base_folder'), self::F_CUSTOM_FOLDER_SELECTION);
//
//		$custom_base_folder_input = new ilTextInputGUI($this->txt(self::F_CUSTOM_BASE_FOLDER_INPUT), self::F_CUSTOM_BASE_FOLDER_INPUT);
//		$custom_base_folder_input->setRequired(true);
//		$custom_base_folder_input->setInfo($this->txt('custom_base_folder_input_info'));
//
//		$option_custom->addSubItem($custom_base_folder_input);
//		$sub_selection->addOption($option_default);
//		$sub_selection->addOption($option_custom);
//
//		$sub_selection->setValue(self::F_DEFAULT_BASE_FOLDER);
//
//		$option->addSubItem($sub_selection);
	}


	public function txt($var = "") {
		return parent::txt('add_new_'.$var); // TODO: Change the autogenerated stub
	}


	/**
	 * @param ilPropertyFormGUI $form
	 * @param ilObjCloud        $obj
	 */
	public function afterSavePluginCreation(ilObjCloud &$obj, ilPropertyFormGUI $form) {
//		if ($form->getInput(self::F_BASE_FOLDER) == self::F_DEFAULT_BASE_FOLDER) {
//			$obj->setRootFolder($obj->getTitle());
//		} else {
//			$obj->setRootFolder($form->getInput(self::F_CUSTOM_BASE_FOLDER_INPUT));
//		}
	}
}

?>