<?php
require_once('./Modules/Cloud/classes/class.ilCloudPluginConfig.php');

/**
 * Class exocConfig
 *
 * @author  Theodor Truffer <tt@studer-raimann.ch>
 */
class exocConfig extends ilCloudPluginConfig {

	public function __construct() {
		parent::__construct('cld_cldh_exoc_config');
	}


//	const F_BASEURL = 'base_url';

//	const F_SSL_VERSION = 'ssl_version';

	/**
	 * @var array
	 */
	protected static $value_cache = array();


	/**
	 * @throws ilCloudException
	 */
	public function checkComplete() {

        if (! true) {
            throw new ilCloudException(- 1, 'Configuration of OwnCloud inclomplete. Please contact your system administrator');
        }

		return true;
	}


//	/**
//	 * @return string
//	 * @throws ilCloudPluginConfigException
//	 */
//	public function getBaseUrl() {
//		return $this->getValue(self::F_BASEURL);
//	}


//	/**
//	 * @return int
//	 */
//	public function getSSLVersion() {
//		return $this->getValue(self::F_SSL_VERSION);
//	}


	/**
	 * @param $key
	 *
	 * @return bool|string
	 * @throws ilCloudPluginConfigException
	 */
	public function getValue($key) {
		if (! isset(self::$value_cache[$key])) {
			self::$value_cache[$key] = parent::getValue($key);
		}

		return self::$value_cache[$key];
	}


	/**
	 * @param $key
	 * @param $value
	 *
	 * @throws ilCloudPluginConfigException
	 */
	public function setValue($key, $value) {
		unset(self::$value_cache[$key]);
		parent::setValue($key, $value); // TODO: Change the autogenerated stub
	}
}

?>
